apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: nfs
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
  selector:
    matchLabels:
      name: nfs-pv