apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  volumeName: nfs-prometheus
  resources:
    requests:
      storage: 10Gi
  storageClassName: prometheus-grafana-class
  selector:
    matchLabels:
      zone1: prometheus
      zone2: grafana
      zone3: alertmanager