apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: monitoring
spec:
  claimRef:
    name: nfs-pvc
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/nfs/home/persistent-volume
    server: 192.168.1.61
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
          - key: zone1
            operator: In
            values:
            - prometheus
          - key: zone2
            operator: In
            values:
            - grafana
          - key: zone3
            operator: In
            values:
            - alertmanager