apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-grafana-pv
  namespace: monitoring
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: prometheus-grafana-class
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/nfs/home/persistent-volume
    server: 192.168.1.61
  # nodeAffinity:
  #   requiredDuringSchedulingIgnoredDuringExecution:
  #     nodeSelectorTerms:
  #     - matchExpressions:
  #       - key: zone1
  #         operator: In
  #         values:
  #         - prometheus
  #       - key: zone2
  #         operator: In
  #         values:
  #         - grafana
  #       - key: zone3
  #         operator: In
  #         values:
  #         - alertmanager