apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-pv
  namespace: monitoring
  labels:
    name: nfs-pv
spec:
  claimRef:
    name: nfs-pvc
    namespace: monitoring
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /var/nfs/home/persistent-volume
    server: 192.168.1.61
