apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: nfs.csi.k8s.io
reclaimPolicy: Retain 
allowVolumeExpansion: true
mountOptions:
  - discard 
volumeBindingMode: Immediate
parameters:
  guaranteedReadWriteLatency: "true" 