apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: prometheus-grafana-class
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: csi-driver.example-vendor.example
reclaimPolicy: Retain 
allowVolumeExpansion: true
mountOptions:
  - discard 
volumeBindingMode: WaitForFirstConsumer
parameters:
  guaranteedReadWriteLatency: "true" 