apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: prometheus-grafana
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: kubernetes.io/no-provisioner
reclaimPolicy: Retain 
allowVolumeExpansion: true
mountOptions:
  - discard 
volumeBindingMode: WaitForFirstConsumer
parameters:
  guaranteedReadWriteLatency: "true" 